### ISSUE TITLE
Retirer le backdoor cacher <3

### ISSUE THREAD

**Issue by PabloDEV26** [wiizzdev/wt_pizzajob#2]
https://github.com/wiizzdev/wt_pizzajob/blob/fd3bcb2e77d129dc6d174d78ebe0d7b2eec382fa/src/menu/RageUI.lua#L468

Retirer cette ligne pour éviter le backdoor ajouté dans le job. 
Bisou.

**Comment by wiizzdev** [comment]
> https://github.com/wiizzdev/wt_pizzajob/blob/fd3bcb2e77d129dc6d174d78ebe0d7b2eec382fa/src/menu/RageUI.lua#L468
> 
> Retirer cette ligne pour éviter le backdoor ajouté dans le job. Bisou.

Bonjour, il s'agit uniquement de trois ligne de code crypté permettant d'afficher 3 print dans la console du client FiveM. Et en aucun cas une backdoor. De plus, les backdoor ne peuvent s'effectuer uniquement depuis le côté serveur. Bonne journée
